#!/usr/bin/env python3
"""
Decode world-atlas TopoJSON into a single SVG path and write src/data/world.ts.

Run once; the output is committed. Nothing about TopoJSON reaches the browser —
the site ships one path string. Regenerate only if the projection changes.

  python3 scripts/build-worldmap.py <land-110m.json>
"""
import json, sys, pathlib

LAT_TOP, LAT_BOT = 84.0, -58.0     # trim Antarctica; keeps Patagonia
W = 1000.0
H = W * (LAT_TOP - LAT_BOT) / 360.0

def decode(topo):
    sx, sy = topo['transform']['scale']
    tx, ty = topo['transform']['translate']
    arcs = []
    for arc in topo['arcs']:
        x = y = 0
        pts = []
        for dx, dy in arc:
            x += dx; y += dy
            pts.append((x * sx + tx, y * sy + ty))
        arcs.append(pts)
    return arcs

def project(lon, lat):
    x = (lon + 180.0) / 360.0 * W
    y = (LAT_TOP - lat) / (LAT_TOP - LAT_BOT) * H
    return x, y

def ring_path(arcs, idxs):
    pts = []
    for i in idxs:
        a = arcs[~i][::-1] if i < 0 else arcs[i]
        pts.extend(a if not pts else a[1:])
    # A ring entirely outside the visible band contributes nothing.
    if all(lat < LAT_BOT for _, lat in pts) or all(lat > LAT_TOP for _, lat in pts):
        return ''
    # Rings that cross the antimeridian (lon jumping +180 <-> -180) would draw a
    # straight line back across the whole map. Split them into separate subpaths.
    runs, cur, prev_lon = [], [], None
    for lon, lat in pts:
        if prev_lon is not None and abs(lon - prev_lon) > 180:
            runs.append(cur); cur = []
        cur.append((lon, lat)); prev_lon = lon
    runs.append(cur)

    subpaths = []
    for run in runs:
        out, last = [], None
        for lon, lat in run:
            x, y = project(lon, lat)
            t = f"{x:.1f},{y:.1f}"
            if t != last:
                out.append(t); last = t
        if len(out) >= 3:
            subpaths.append('M' + 'L'.join(out) + 'Z')
    return ''.join(subpaths)

topo = json.load(open(sys.argv[1]))
arcs = decode(topo)
paths = []
for geom in topo['objects']['land']['geometries']:
    polys = geom['arcs'] if geom['type'] == 'MultiPolygon' else [geom['arcs']]
    for poly in polys:
        for ring in poly:
            p = ring_path(arcs, ring)
            if p: paths.append(p)

d = ''.join(paths)
out = pathlib.Path('src/data/world.ts')
out.write_text(
    "// Generated by scripts/build-worldmap.py from world-atlas land-110m.\n"
    "// Equirectangular, Antarctica trimmed. Do not edit by hand.\n"
    f"export const WORLD_W = {W:.0f};\n"
    f"export const WORLD_H = {H:.1f};\n"
    f"export const LAT_TOP = {LAT_TOP};\n"
    f"export const LAT_BOT = {LAT_BOT};\n"
    f'export const WORLD_PATH = "{d}";\n'
    "\n"
    "export function project(lon: number, lat: number): [number, number] {\n"
    "  return [\n"
    "    ((lon + 180) / 360) * WORLD_W,\n"
    "    ((LAT_TOP - lat) / (LAT_TOP - LAT_BOT)) * WORLD_H,\n"
    "  ];\n"
    "}\n")
print(f"world.ts: {len(paths)} rings, {len(d)/1024:.0f} KB path, viewBox 0 0 {W:.0f} {H:.1f}")
